In [2]:
import pandas as pd

# List of file names
file_names = [f'FF_OzMatched_{i}.csv' for i in range(1, 11)]

# Initialize an empty DataFrame
combined_df = pd.DataFrame()

# Loop through each file and append its contents to the combined DataFrame
for file in file_names:
    temp_df = pd.read_csv(file)
    combined_df = combined_df.append(temp_df, ignore_index=True)

# Save the combined DataFrame to a new CSV file
combined_df.to_csv('FF_OzMatched_full.csv', index=False)

# Display the combined DataFrame (optional)
combined_df.head(None)

/home/iyer95/.conda/envs/CLA/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3258: DtypeWarning: Columns (1,2) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,Class,Lipid,OzESI_Intensity,Parent_Ion,Product_Ion,Retention_Time,Sample_ID,Transition,Unnamed: 0.1
0,0,NaN,NaN,42.920002,584.4,437.3,0.044183,11282023_DOD94_F3_WT_cereb_O3on_01,584.4 -> 437.3,0
1,1,NaN,NaN,42.540005,584.4,437.3,0.088567,11282023_DOD94_F3_WT_cereb_O3on_01,584.4 -> 437.3,1
2,2,NaN,NaN,43.180004,584.4,437.3,0.132967,11282023_DOD94_F3_WT_cereb_O3on_01,584.4 -> 437.3,2
3,3,NaN,NaN,42.780003,584.4,437.3,0.177367,11282023_DOD94_F3_WT_cereb_O3on_01,584.4 -> 437.3,3
4,4,NaN,NaN,42.720001,584.4,437.3,0.221783,11282023_DOD94_F3_WT_cereb_O3on_01,584.4 -> 437.3,4
...,...,...,...,...,...,...,...,...,...,...
4137608,413759,TAG,"[TG(59:11),TG(58:4)]_FA18:1",41.080002,956.9,657.6,24.779117,12012023_FAD173_M1_5xFAD_liver_O3on_01,956.9 -> 657.6,4137608
4137609,413760,TAG,"[TG(59:11),TG(58:4)]_FA18:1",40.980003,956.9,657.6,24.823533,12012023_FAD173_M1_5xFAD_liver_O3on_01,956.9 -> 657.6,4137609
4137610,413761,TAG,"[TG(59:11),TG(58:4)]_FA18:1",40.980003,956.9,657.6,24.867933,12012023_FAD173_M1_5xFAD_liver_O3on_01,956.9 -> 657.6,4137610
4137611,413762,TAG,"[TG(59:11),TG(58:4)]_FA18:1",40.960003,956.9,657.6,24.912333,12012023_FAD173_M1_5xFAD_liver_O3on_01,956.9 -> 657.6,4137611
4137612,413763,TAG,"[TG(59:11),TG(58:4)]_FA18:1",40.900002,956.9,657.6,24.956750,12012023_FAD173_M1_5xFAD_liver_O3on_01,956.9 -> 657.6,4137612