In [ ]:
##Import packages

In [5]:
import pandas as pd
import re

In [35]:

# Define empty lists to hold the numbers and gene codes
numbers_for_gene = []
genes = []

# Open the file and parse each line
with open('./Gene_Database/genes.txt', 'r') as file:
    for line in file:
        # Use a regular expression to find the number and gene code
        match = re.search(r'VALUES \((\d+), \'(\w+)\'', line)
        if match:
            # If a match was found, add the number and gene code to the lists
            numbers_for_gene.append(int(match.group(1)))
            genes.append(match.group(2))

# Create a dataframe from the lists
df_genes = pd.DataFrame({
    'Number': numbers,
    'Gene': genes
})

print(df_genes)

     Number    Gene
0    125981   ACER1
1     10715   CERS1
2     29956   CERS2
3    204219   CERS3
4     79603   CERS4
..      ...     ...
131    3992   FADS1
132    9415   FADS2
133   54898  ELOVL2
134   83401  ELOVL3
135    6785  ELOVL4

[136 rows x 2 columns]

In [43]:

# Define empty lists to hold the numbers and gene codes
reactions = []
Gene_Code = []

# Open the file and parse each line
# Open the file and parse each line
with open('./Gene_Database/genes2lipid.txt', 'r') as file:
    for line in file:
        # Use a regular expression to find the reaction number and gene code
        print(line)
        match = re.search(r'VALUES \((\d+), *(\d+)\)', line)
        if match:
            # If a match was found, add the reaction number and gene code to the lists
            reactions.append(int(match.group(1)))
            Gene_Code.append(int(match.group(2)))

# Create a dataframe from the lists
df_gene_2_reaction = pd.DataFrame({
    'Reaction': reactions,
    'Gene Code': Gene_Code
})

print(df_gene_2_reaction)

print(len(df_gene_2_reaction))

-- biopan_reaction_gene table --

INSERT INTO biopan_reaction_gene VALUES (1, 1606);

INSERT INTO biopan_reaction_gene VALUES (1, 1607);

INSERT INTO biopan_reaction_gene VALUES (1, 8527);

INSERT INTO biopan_reaction_gene VALUES (1, 8526);

INSERT INTO biopan_reaction_gene VALUES (1, 1608);

INSERT INTO biopan_reaction_gene VALUES (1, 160851);

INSERT INTO biopan_reaction_gene VALUES (1, 9162);

INSERT INTO biopan_reaction_gene VALUES (1, 139189);

INSERT INTO biopan_reaction_gene VALUES (1, 1609);

INSERT INTO biopan_reaction_gene VALUES (1, 8525);



INSERT INTO biopan_reaction_gene VALUES (2, 8611);

INSERT INTO biopan_reaction_gene VALUES (2, 8612);

INSERT INTO biopan_reaction_gene VALUES (2, 8613);



INSERT INTO biopan_reaction_gene VALUES (3, 1040);

INSERT INTO biopan_reaction_gene VALUES (3, 8760);

INSERT INTO biopan_reaction_gene VALUES (3, 114971);



INSERT INTO biopan_reaction_gene VALUES (4, 1040);

INSERT INTO biopan_reaction_gene VALUES (4, 8760);

INSERT INTO biopan_reaction_gene VALUES (4, 10423);



INSERT INTO biopan_reaction_gene VALUES (5, 1040);

INSERT INTO biopan_reaction_gene VALUES (5, 9791);



INSERT INTO biopan_reaction_gene VALUES (6, 23761);



INSERT INTO biopan_reaction_gene VALUES (7, 81490);



INSERT INTO biopan_reaction_gene VALUES (8, 10400);



INSERT INTO biopan_reaction_gene VALUES (9, 9791);



INSERT INTO biopan_reaction_gene VALUES (10, 8228);

INSERT INTO biopan_reaction_gene VALUES (10, 150379);



INSERT INTO biopan_reaction_gene VALUES (11, 84649);



INSERT INTO biopan_reaction_gene VALUES (12, 54675);



INSERT INTO biopan_reaction_gene VALUES (13, 81537);

INSERT INTO biopan_reaction_gene VALUES (13, 130367);



INSERT INTO biopan_reaction_gene VALUES (14, 8877);

INSERT INTO biopan_reaction_gene VALUES (14, 5684);



INSERT INTO biopan_reaction_gene VALUES (15, 125981);

INSERT INTO biopan_reaction_gene VALUES (15, 427);

INSERT INTO biopan_reaction_gene VALUES (15, 56624);



INSERT INTO biopan_reaction_gene VALUES (16, 10715);

INSERT INTO biopan_reaction_gene VALUES (16, 29956);

INSERT INTO biopan_reaction_gene VALUES (16, 204219);

INSERT INTO biopan_reaction_gene VALUES (16, 79603);

INSERT INTO biopan_reaction_gene VALUES (16, 91012);

INSERT INTO biopan_reaction_gene VALUES (16, 253782);



INSERT INTO biopan_reaction_gene VALUES (17,259230);

INSERT INTO biopan_reaction_gene VALUES (17,166929);

INSERT INTO biopan_reaction_gene VALUES (17,10087);



INSERT INTO biopan_reaction_gene VALUES (18,6609);

INSERT INTO biopan_reaction_gene VALUES (18,6610);

INSERT INTO biopan_reaction_gene VALUES (18,55512);



INSERT INTO biopan_reaction_gene VALUES (19,259230);

INSERT INTO biopan_reaction_gene VALUES (19,166929);



INSERT INTO biopan_reaction_gene VALUES (20,259230);

INSERT INTO biopan_reaction_gene VALUES (20,166929);

INSERT INTO biopan_reaction_gene VALUES (20,6609);



INSERT INTO biopan_reaction_gene VALUES (21,8560);

INSERT INTO biopan_reaction_gene VALUES (21,123099);



INSERT INTO biopan_reaction_gene VALUES (22,79888);

INSERT INTO biopan_reaction_gene VALUES (22,54947);

INSERT INTO biopan_reaction_gene VALUES (22,10162);

INSERT INTO biopan_reaction_gene VALUES (22,254531);



INSERT INTO biopan_reaction_gene VALUES (23,30814);

INSERT INTO biopan_reaction_gene VALUES (23,5320);

INSERT INTO biopan_reaction_gene VALUES (23,26279);

INSERT INTO biopan_reaction_gene VALUES (23,64600);

INSERT INTO biopan_reaction_gene VALUES (23,5319);

INSERT INTO biopan_reaction_gene VALUES (23,5321);

INSERT INTO biopan_reaction_gene VALUES (23,100137049);

INSERT INTO biopan_reaction_gene VALUES (23,8605);

INSERT INTO biopan_reaction_gene VALUES (23,283748);

INSERT INTO biopan_reaction_gene VALUES (23,123745);

INSERT INTO biopan_reaction_gene VALUES (23,255189);



INSERT INTO biopan_reaction_gene VALUES (24,10554);

INSERT INTO biopan_reaction_gene VALUES (24,10555);

INSERT INTO biopan_reaction_gene VALUES (24,56894);

INSERT INTO biopan_reaction_gene VALUES (24,56895);

INSERT INTO biopan_reaction_gene VALUES (24,55326);



INSERT INTO biopan_reaction_gene VALUES (25,5321);

INSERT INTO biopan_reaction_gene VALUES (25,283748);

INSERT INTO biopan_reaction_gene VALUES (25,123745);

INSERT INTO biopan_reaction_gene VALUES (25,255189);



INSERT INTO biopan_reaction_gene VALUES (26,154141);

INSERT INTO biopan_reaction_gene VALUES (26,129642);

INSERT INTO biopan_reaction_gene VALUES (26,10162);

INSERT INTO biopan_reaction_gene VALUES (26,254531);



INSERT INTO biopan_reaction_gene VALUES (27,8605);



INSERT INTO biopan_reaction_gene VALUES (28,79143);



INSERT INTO biopan_reaction_gene VALUES (29,283748);

INSERT INTO biopan_reaction_gene VALUES (29,123745);



INSERT INTO biopan_reaction_gene VALUES (30,154141);

INSERT INTO biopan_reaction_gene VALUES (30,10162);

INSERT INTO biopan_reaction_gene VALUES (30,254531);



INSERT INTO biopan_reaction_gene VALUES (31,30814);

INSERT INTO biopan_reaction_gene VALUES (31,5320);

INSERT INTO biopan_reaction_gene VALUES (31,64600);



INSERT INTO biopan_reaction_gene VALUES (32,9926);

INSERT INTO biopan_reaction_gene VALUES (32,54675);



INSERT INTO biopan_reaction_gene VALUES (33,283748);

INSERT INTO biopan_reaction_gene VALUES (33,255189);

INSERT INTO biopan_reaction_gene VALUES (33,54675);



INSERT INTO biopan_reaction_gene VALUES (34,5537);

INSERT INTO biopan_reaction_gene VALUES (34,5338);



INSERT INTO biopan_reaction_gene VALUES (35,23236);

INSERT INTO biopan_reaction_gene VALUES (35,5330);

INSERT INTO biopan_reaction_gene VALUES (35,5331);

INSERT INTO biopan_reaction_gene VALUES (35,5332);

INSERT INTO biopan_reaction_gene VALUES (35,5333);

INSERT INTO biopan_reaction_gene VALUES (35,113026);

INSERT INTO biopan_reaction_gene VALUES (35,84812);

INSERT INTO biopan_reaction_gene VALUES (35,51196);

INSERT INTO biopan_reaction_gene VALUES (35,5335);

INSERT INTO biopan_reaction_gene VALUES (35,5336);



INSERT INTO biopan_reaction_gene VALUES (37,56994);



INSERT INTO biopan_reaction_gene VALUES (38,10390);



INSERT INTO biopan_reaction_gene VALUES (39,4245);



INSERT INTO biopan_reaction_gene VALUES (40,57140);

INSERT INTO biopan_reaction_gene VALUES (40,80339);



INSERT INTO biopan_reaction_gene VALUES (41,64781);



INSERT INTO biopan_reaction_gene VALUES (42,5524);



INSERT INTO biopan_reaction_gene VALUES (43,6610);



INSERT INTO biopan_reaction_gene VALUES (44,6901);



INSERT INTO biopan_reaction_gene VALUES (45,5297);

INSERT INTO biopan_reaction_gene VALUES (45,55361);

INSERT INTO biopan_reaction_gene VALUES (45,55300);

INSERT INTO biopan_reaction_gene VALUES (45,8394);

INSERT INTO biopan_reaction_gene VALUES (45,8395);

INSERT INTO biopan_reaction_gene VALUES (45,714107);



INSERT INTO biopan_reaction_gene VALUES (46,8867);

INSERT INTO biopan_reaction_gene VALUES (46,8871);

INSERT INTO biopan_reaction_gene VALUES (46,714107);

INSERT INTO biopan_reaction_gene VALUES (46,8776);

INSERT INTO biopan_reaction_gene VALUES (46,8898);

INSERT INTO biopan_reaction_gene VALUES (46,8897);

INSERT INTO biopan_reaction_gene VALUES (46,9110);

INSERT INTO biopan_reaction_gene VALUES (46,9107);

INSERT INTO biopan_reaction_gene VALUES (46,9108);

INSERT INTO biopan_reaction_gene VALUES (46,55613);

INSERT INTO biopan_reaction_gene VALUES (46,66036);

INSERT INTO biopan_reaction_gene VALUES (46,64419);

INSERT INTO biopan_reaction_gene VALUES (46,5728);



INSERT INTO biopan_reaction_gene VALUES (47,200576);

INSERT INTO biopan_reaction_gene VALUES (47,8394);

INSERT INTO biopan_reaction_gene VALUES (47,8395);

INSERT INTO biopan_reaction_gene VALUES (47,23396);

INSERT INTO biopan_reaction_gene VALUES (47,5305);

INSERT INTO biopan_reaction_gene VALUES (47,8396);

INSERT INTO biopan_reaction_gene VALUES (47,79837);



INSERT INTO biopan_reaction_gene VALUES (48,9896);

INSERT INTO biopan_reaction_gene VALUES (48,4952);

INSERT INTO biopan_reaction_gene VALUES (48,56623);

INSERT INTO biopan_reaction_gene VALUES (48,5728);



INSERT INTO biopan_reaction_gene VALUES (49,5290);

INSERT INTO biopan_reaction_gene VALUES (49,5291);

INSERT INTO biopan_reaction_gene VALUES (49,5293);

INSERT INTO biopan_reaction_gene VALUES (49,5294);



INSERT INTO biopan_reaction_gene VALUES (50,51763);

INSERT INTO biopan_reaction_gene VALUES (50,3635);

INSERT INTO biopan_reaction_gene VALUES (50,27124);

INSERT INTO biopan_reaction_gene VALUES (50,5728);



INSERT INTO biopan_reaction_gene VALUES (51,5168);



INSERT INTO biopan_reaction_gene VALUES (52,30049);



INSERT INTO biopan_reaction_gene VALUES (53,60481);

INSERT INTO biopan_reaction_gene VALUES (53,79071);



INSERT INTO biopan_reaction_gene VALUES (54,9415);



INSERT INTO biopan_reaction_gene VALUES (55,9415);



INSERT INTO biopan_reaction_gene VALUES (56,60481);

INSERT INTO biopan_reaction_gene VALUES (56,79993);



INSERT INTO biopan_reaction_gene VALUES (57,79071);



INSERT INTO biopan_reaction_gene VALUES (58,6319);



INSERT INTO biopan_reaction_gene VALUES (59,9415);



INSERT INTO biopan_reaction_gene VALUES (60,60481);



INSERT INTO biopan_reaction_gene VALUES (61,3992);



INSERT INTO biopan_reaction_gene VALUES (62,83401);



INSERT INTO biopan_reaction_gene VALUES (63,83401);



INSERT INTO biopan_reaction_gene VALUES (64,83401);



INSERT INTO biopan_reaction_gene VALUES (65,64834);

INSERT INTO biopan_reaction_gene VALUES (65,79993);

INSERT INTO biopan_reaction_gene VALUES (65,83401);



INSERT INTO biopan_reaction_gene VALUES (66,64834);

INSERT INTO biopan_reaction_gene VALUES (66,79993);

INSERT INTO biopan_reaction_gene VALUES (66,83401);



INSERT INTO biopan_reaction_gene VALUES (67,64834);

INSERT INTO biopan_reaction_gene VALUES (67,79993);

INSERT INTO biopan_reaction_gene VALUES (67,83401);



INSERT INTO biopan_reaction_gene VALUES (68,64834);

INSERT INTO biopan_reaction_gene VALUES (68,83401);



INSERT INTO biopan_reaction_gene VALUES (69,6785);



INSERT INTO biopan_reaction_gene VALUES (70,6785);



INSERT INTO biopan_reaction_gene VALUES (71,3992);



INSERT INTO biopan_reaction_gene VALUES (72,60481);

INSERT INTO biopan_reaction_gene VALUES (72,54898);



INSERT INTO biopan_reaction_gene VALUES (73,54898);



INSERT INTO biopan_reaction_gene VALUES (74,9415);



INSERT INTO biopan_reaction_gene VALUES (75,9415);



INSERT INTO biopan_reaction_gene VALUES (76,60481);



INSERT INTO biopan_reaction_gene VALUES (77,3992);



INSERT INTO biopan_reaction_gene VALUES (78,60481);

INSERT INTO biopan_reaction_gene VALUES (78,54898);



INSERT INTO biopan_reaction_gene VALUES (79,54898);



INSERT INTO biopan_reaction_gene VALUES (80,9415);



INSERT INTO biopan_reaction_gene VALUES (81,54898);

INSERT INTO biopan_reaction_gene VALUES (81,6785);



INSERT INTO biopan_reaction_gene VALUES (82,56994);



INSERT INTO biopan_reaction_gene VALUES (83,10390);



INSERT INTO biopan_reaction_gene VALUES (84,387521);



INSERT INTO biopan_reaction_gene VALUES (85,10390);

INSERT INTO biopan_reaction_gene VALUES (85,5537);

INSERT INTO biopan_reaction_gene VALUES (85,8611);

INSERT INTO biopan_reaction_gene VALUES (85,8612);

INSERT INTO biopan_reaction_gene VALUES (85,56994);



INSERT INTO biopan_reaction_gene VALUES (86,30814);

INSERT INTO biopan_reaction_gene VALUES (86,5320);

INSERT INTO biopan_reaction_gene VALUES (86,26279);

INSERT INTO biopan_reaction_gene VALUES (86,64600);

INSERT INTO biopan_reaction_gene VALUES (86,5319);

INSERT INTO biopan_reaction_gene VALUES (86,5321);

INSERT INTO biopan_reaction_gene VALUES (86,100137049);

INSERT INTO biopan_reaction_gene VALUES (86,8605);

INSERT INTO biopan_reaction_gene VALUES (86,283748);

INSERT INTO biopan_reaction_gene VALUES (86,123745);

INSERT INTO biopan_reaction_gene VALUES (86,255189);



INSERT INTO biopan_reaction_gene VALUES (87,30814);

INSERT INTO biopan_reaction_gene VALUES (87,5320);

INSERT INTO biopan_reaction_gene VALUES (87,26279);

INSERT INTO biopan_reaction_gene VALUES (87,64600);

INSERT INTO biopan_reaction_gene VALUES (87,5319);

INSERT INTO biopan_reaction_gene VALUES (87,5321);

INSERT INTO biopan_reaction_gene VALUES (87,100137049);

INSERT INTO biopan_reaction_gene VALUES (87,8605);

INSERT INTO biopan_reaction_gene VALUES (87,283748);

INSERT INTO biopan_reaction_gene VALUES (87,123745);

INSERT INTO biopan_reaction_gene VALUES (87,255189);



INSERT INTO biopan_reaction_gene VALUES (88,8605);



INSERT INTO biopan_reaction_gene VALUES (89,8605);



INSERT INTO biopan_reaction_gene VALUES (90,5537);

INSERT INTO biopan_reaction_gene VALUES (90,5338);



INSERT INTO biopan_reaction_gene VALUES (91,5338);



INSERT INTO biopan_reaction_gene VALUES (92,5537);

INSERT INTO biopan_reaction_gene VALUES (92,5338);



INSERT INTO biopan_reaction_gene VALUES (93,5338);



INSERT INTO biopan_reaction_gene VALUES (94,79888);



INSERT INTO biopan_reaction_gene VALUES (95,10715);

INSERT INTO biopan_reaction_gene VALUES (95,29956);

INSERT INTO biopan_reaction_gene VALUES (95,204219);

INSERT INTO biopan_reaction_gene VALUES (95,79603);

INSERT INTO biopan_reaction_gene VALUES (95,91012);

INSERT INTO biopan_reaction_gene VALUES (95,253782);



INSERT INTO biopan_reaction_gene VALUES (96,8877);

INSERT INTO biopan_reaction_gene VALUES (96,5684);



INSERT INTO biopan_reaction_gene VALUES (97,81537);

INSERT INTO biopan_reaction_gene VALUES (97,130367);
     Reaction  Gene Code
0           1       1606
1           1       1607
2           1       8527
3           1       8526
4           1       1608
..        ...        ...
244        95     253782
245        96       8877
246        96       5684
247        97      81537
248        97     130367

[249 rows x 2 columns]
249

In [48]:
import pandas as pd
import re

import pandas as pd
import re

# Read the file
with open('./Gene_Database/Lipid Reactions.txt', 'r') as file:    # replace 'filename.txt' with your file name
    text = file.read()


# Regular expression pattern to capture required data
pattern = r"INSERT INTO biopan_reaction VALUES \((\d+), (.*), '(.*?)', '(.*?)',"

# Find all matches and create a list of dictionaries
matches = re.findall(pattern, text)
data = [{'reaction_code': int(m[0]), 'Lipid 1': m[1].split(',')[0].replace("E'", ""), 'Lipid 2': m[1].split(',')[1].replace("'", ""), 'Class': m[2], 'reaction_type': m[3]} for m in matches]

# Create pandas DataFrame
df = pd.DataFrame(data)
print(df)

    reaction_code  Lipid 1 Lipid 2  \
0               1      'DG      PA
1               2      'PA      DG
2               3      'PA      PG
3               4      'PA      PI
4               5      'PA      PS
..            ...      ...     ...
92             93   'P-LPE   P-LPA
93             94   'O-LPC    O-PC
94             95   'dhSPB   dhCer
95             96   'dhSPB  dhSPBP
96             97  'dhSPBP   dhSPB

                                             Class reaction_type
0                               Biosynthesis of PA  Homo sapiens
1         Biosynthesis of Mono/Di/Triacylglycerols  Homo sapiens
2                               Biosynthesis of PG  Homo sapiens
3                               Biosynthesis of PI  Homo sapiens
4                               Biosynthesis of PS  Homo sapiens
..                                             ...           ...
92                           Biosynthesis of P-LPA  Homo sapiens
93                            Biosynthesis of O-PC  Homo sapiens
94              Biosynthesis of Dihydrosphingosine  Homo sapiens
95  Biosynthesis of Dihydrosphingosine 1-phosphate  Homo sapiens
96              Biosynthesis of Dihydrosphingosine  Homo sapiens

[97 rows x 5 columns]

In [54]:

# Read the file
with open('./Gene_Database/Lipid Reactions.txt', 'r') as file:    # replace 'filename.txt' with your file name
    text = file.read()

# Regular expression pattern to capture required data
# I've included \s* to match any number of spaces
pattern = r"INSERT INTO biopan_reaction VALUES \((\d+),\s*(.*?),\s*'(.*?)',\s*'(.*?)',"

# Find all matches and create a list of dictionaries
matches = re.findall(pattern, text)
data = [{'reaction_code': int(m[0]), 'Lipid 1': m[1].split(',')[0].replace("E'", ""), 'Lipid 2': m[1].split(',')[1].replace("'", ""), 'Class': m[2], 'reaction_type': m[3]} for m in matches]

# Create pandas DataFrame
df = pd.DataFrame(data)

In [55]:
df

,reaction_code,Lipid 1,Lipid 2,Class,reaction_type
0,1,'DG,PA,Glycerolipids and Glycerophospholipids,Biosynthesis of PA
1,2,'PA,DG,Glycerolipids and Glycerophospholipids,Biosynthesis of Mono/Di/Triacylglycerols
2,3,'PA,PG,Glycerolipids and Glycerophospholipids,Biosynthesis of PG
3,4,'PA,PI,Glycerolipids and Glycerophospholipids,Biosynthesis of PI
4,5,'PA,PS,Glycerolipids and Glycerophospholipids,Biosynthesis of PS
...,...,...,...,...,...
92,93,'P-LPE,P-LPA,Glycerolipids and Glycerophospholipids,Biosynthesis of P-LPA
93,94,'O-LPC,O-PC,Glycerolipids and Glycerophospholipids,Biosynthesis of O-PC
94,95,'dhSPB,dhCer,Sphingolipids,Biosynthesis of Dihydrosphingosine
95,96,'dhSPB,dhSPBP,Sphingolipids,Biosynthesis of Dihydrosphingosine 1-phosphate
96,97,'dhSPBP,dhSPB,Sphingolipids,Biosynthesis of Dihydrosphingosine

,reaction_code,Lipid 1,Lipid 2,Class,reaction_type
0,1,'DG,PA,Biosynthesis of PA,Homo sapiens
1,2,'PA,DG,Biosynthesis of Mono/Di/Triacylglycerols,Homo sapiens
2,3,'PA,PG,Biosynthesis of PG,Homo sapiens
3,4,'PA,PI,Biosynthesis of PI,Homo sapiens
4,5,'PA,PS,Biosynthesis of PS,Homo sapiens
...,...,...,...,...,...
92,93,'P-LPE,P-LPA,Biosynthesis of P-LPA,Homo sapiens
93,94,'O-LPC,O-PC,Biosynthesis of O-PC,Homo sapiens
94,95,'dhSPB,dhCer,Biosynthesis of Dihydrosphingosine,Homo sapiens
95,96,'dhSPB,dhSPBP,Biosynthesis of Dihydrosphingosine 1-phosphate,Homo sapiens
96,97,'dhSPBP,dhSPB,Biosynthesis of Dihydrosphingosine,Homo sapiens

In [56]:
df2 = df_gene_2_reaction.merge(df, left_on='Reaction', right_on='reaction_code', how='left')

In [59]:
df2 = df2.merge(df_genes, left_on='Gene Code', right_on='Number', how='left')

In [60]:
df2

,Reaction,Gene Code,reaction_code,Lipid 1,Lipid 2,Class,reaction_type,Number,Gene
0,1,1606,1,'DG,PA,Glycerolipids and Glycerophospholipids,Biosynthesis of PA,1606,DGKA
1,1,1607,1,'DG,PA,Glycerolipids and Glycerophospholipids,Biosynthesis of PA,1607,DGKB
2,1,8527,1,'DG,PA,Glycerolipids and Glycerophospholipids,Biosynthesis of PA,8527,DGKD
3,1,8526,1,'DG,PA,Glycerolipids and Glycerophospholipids,Biosynthesis of PA,8526,DGKE
4,1,1608,1,'DG,PA,Glycerolipids and Glycerophospholipids,Biosynthesis of PA,1608,DGKG
...,...,...,...,...,...,...,...,...,...
244,95,253782,95,'dhSPB,dhCer,Sphingolipids,Biosynthesis of Dihydrosphingosine,253782,CERS6
245,96,8877,96,'dhSPB,dhSPBP,Sphingolipids,Biosynthesis of Dihydrosphingosine 1-phosphate,8877,SPHK1
246,96,5684,96,'dhSPB,dhSPBP,Sphingolipids,Biosynthesis of Dihydrosphingosine 1-phosphate,5684,SPHK2
247,97,81537,97,'dhSPBP,dhSPB,Sphingolipids,Biosynthesis of Dihydrosphingosine,81537,SGPP1
248,97,130367,97,'dhSPBP,dhSPB,Sphingolipids,Biosynthesis of Dihydrosphingosine,130367,SGPP2

In [61]:
df2['Lipid 1'] = df2['Lipid 1'].str.replace("'", "")

In [63]:
df2

,Reaction,Gene Code,reaction_code,Lipid 1,Lipid 2,Class,reaction_type,Number,Gene
0,1,1606,1,DG,PA,Glycerolipids and Glycerophospholipids,Biosynthesis of PA,1606,DGKA
1,1,1607,1,DG,PA,Glycerolipids and Glycerophospholipids,Biosynthesis of PA,1607,DGKB
2,1,8527,1,DG,PA,Glycerolipids and Glycerophospholipids,Biosynthesis of PA,8527,DGKD
3,1,8526,1,DG,PA,Glycerolipids and Glycerophospholipids,Biosynthesis of PA,8526,DGKE
4,1,1608,1,DG,PA,Glycerolipids and Glycerophospholipids,Biosynthesis of PA,1608,DGKG
...,...,...,...,...,...,...,...,...,...
244,95,253782,95,dhSPB,dhCer,Sphingolipids,Biosynthesis of Dihydrosphingosine,253782,CERS6
245,96,8877,96,dhSPB,dhSPBP,Sphingolipids,Biosynthesis of Dihydrosphingosine 1-phosphate,8877,SPHK1
246,96,5684,96,dhSPB,dhSPBP,Sphingolipids,Biosynthesis of Dihydrosphingosine 1-phosphate,5684,SPHK2
247,97,81537,97,dhSPBP,dhSPB,Sphingolipids,Biosynthesis of Dihydrosphingosine,81537,SGPP1
248,97,130367,97,dhSPBP,dhSPB,Sphingolipids,Biosynthesis of Dihydrosphingosine,130367,SGPP2

In [64]:
unique = set(list(df2['Lipid 1'].unique())+list(df2['Lipid 1'].unique()))

In [65]:
unique

{'Cer',
 'Cer1P',
 'DG',
 'FA(16:0)',
 'FA(16:1)',
 'FA(18:0)',
 'FA(18:1)',
 'FA(18:2)',
 'FA(18:3)',
 'FA(18:4)',
 'FA(20:0)',
 'FA(20:1)',
 'FA(20:2)',
 'FA(20:3)',
 'FA(20:4)',
 'FA(20:5)',
 'FA(22:0)',
 'FA(22:1)',
 'FA(22:4)',
 'FA(22:5)',
 'FA(24:0)',
 'FA(24:4)',
 'FA(24:5)',
 'FA(24:6)',
 'FA(26:0)',
 'FA(28:0)',
 'LPA',
 'LPC',
 'LPE',
 'LPG',
 'LPI',
 'LPS',
 'MG',
 'O-DG',
 'O-LPC',
 'O-LPE',
 'O-PC',
 'O-PE',
 'P-LPC',
 'P-LPE',
 'P-PC',
 'P-PE',
 'PA',
 'PC',
 'PE',
 'PG',
 'PI',
 'PIP',
 'PIP2',
 'PIP3',
 'PS',
 'SM',
 'SPB',
 'SPBP',
 'TG',
 'dhCer',
 'dhSM',
 'dhSPB',
 'dhSPBP'}

In [66]:
up = ["DG","TG","FA"]
down = ["Cer","SM","PC"]

In [ ]:
up_match = df2['Lipid 1'].isin(up)
down_match = df2['Lipid 2'].isin(down)

# Create a new DataFrame with rows where both conditions are True
new_df = df2[up_match & down_match][['Lipid 1', 'Lipid 2', 'Gene']]

In [69]:
new_df

    Lipid 1 Lipid 2   Gene
110      DG      PC  CHPT1

In [73]:
###sUB CLASSES NEEDED

'Cer', ##Should also be dhCer
 'Cer1P',
    DG'
    fa
    LPC',
 'LPE',
 'LPG',
 'LPI',
 'LPS',
    'MG',
 'O-DG',
 'O-LPC',
 'O-LPE',
 'O-PC',
 'O-PE',
 'P-LPC',
 'P-LPE',
 'P-PC',
 'P-PE',
 'PA',
 'PC',
 'PE',
 'PG',
 'PI',
 'PIP',

 'PS',
 'SM',

 'TG',

 'dhSM',

    ##We have DAG O and TAG O  why not more?
    TG(O-45:0)
    ###DG(dO-37:4)
    
    ###wHAT ABOUT PS DERIVATIVES?
    ## 1-O Ceramides
    ##omega-linoleoyloxy ceramides

IndentationError: unexpected indent (<ipython-input-73-6789f9f6190a>, line 4)

In [ ]:
##Sub types