In [48]:
import pandas as pd
directory = 'Projects/AMP/results/fame_mix/'
file_name_ON = 'FAME_OzON.xlsx'
file_name_OFF = 'FAME_OzOFF.xlsx'

OzON_df = pd.read_excel(directory + file_name_ON)
OzOFF_df = pd.read_excel(directory + file_name_OFF)

In [49]:
OzOFF_df

,Group_Sample,Lipid,Biology,Genotype,Cage,Mouse,Parent_Ion,Product_Ion,Peak_Retention_Time,Peak_Height,FWHM,Start,Stop,Peak_Width,Peak_Area,Peak_Data_Retention_Times,Peak_Data_Intensities,Full_Data_Retention_Times,Full_Data_Intensities,FAC
0,0,11:0,NaN,NaN,NaN,NaN,353.3,183,4.37,238662.66,0.10,4.32,4.43,5.55,25404.85,"[4.32, 4.35, 4.37, 4.4, 4.43]","[113512.62, 231104.95, 238662.66, 121754.03, 5...","[0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.28, 41.28, 41.28, 41.24, 41.2, 41.14, 41.1...",['11:0']
1,1,12:0,NaN,NaN,NaN,NaN,367.3,183,4.82,705102.31,0.13,4.77,4.90,5.79,97572.56,"[4.77, 4.79, 4.82, 4.84, 4.87, 4.9]","[100902.51, 443251.91, 705102.31, 651051.06, 3...","[0.02, 0.04, 0.07, 0.1, 0.12, 0.15, 0.17, 0.2,...","[41.34, 41.34, 41.32, 46.36, 48.6, 46.24, 41.1...",['12:0']
2,2,13:0,NaN,NaN,NaN,NaN,381.3,183,5.53,504149.34,0.13,5.47,5.60,6.01,69764.54,"[5.47, 5.5, 5.53, 5.55, 5.58, 5.6]","[135906.56, 374686.53, 504149.34, 422285.03, 2...","[0.02, 0.04, 0.07, 0.09, 0.12, 0.15, 0.17, 0.2...","[41.3, 41.28, 41.32, 41.3, 60.42, 69.18, 60.44...",['13:0']
3,3,14:0,NaN,NaN,NaN,NaN,395.4,183,6.34,1573354.88,0.13,6.28,6.42,5.86,217721.97,"[6.28, 6.31, 6.34, 6.36, 6.39, 6.42]","[279456.03, 1011152.69, 1573354.88, 1477465.12...","[0.01, 0.04, 0.07, 0.09, 0.12, 0.15, 0.17, 0.2...","[41.3, 41.32, 41.36, 41.36, 41.32, 41.28, 41.2...",['14:0']
4,4,14:1(9Z),NaN,NaN,NaN,NaN,393.4,183,5.31,834262.56,0.13,5.24,5.37,6.44,115445.85,"[5.24, 5.26, 5.29, 5.31, 5.34, 5.37]","[75123.2, 456994.03, 817670.06, 834262.56, 535...","[0.02, 0.04, 0.07, 0.09, 0.12, 0.15, 0.17, 0.2...","[41.3, 41.3, 41.32, 41.3, 50.38, 54.54, 50.38,...",['14:1']
5,5,15:0,NaN,NaN,NaN,NaN,409.4,183,7.28,857884.56,0.16,7.20,7.36,6.46,146110.37,"[7.2, 7.23, 7.25, 7.28, 7.31, 7.33, 7.36]","[101135.41, 447497.59, 795775.25, 857884.56, 6...","[0.01, 0.04, 0.07, 0.09, 0.12, 0.14, 0.17, 0.2...","[41.22, 41.3, 41.3, 41.28, 41.26, 41.26, 41.24...",['15:0']
6,6,15:1,NaN,NaN,NaN,NaN,407.2,183,6.07,882000.25,0.13,5.99,6.13,6.52,122051.82,"[5.99, 6.02, 6.05, 6.07, 6.1, 6.13]","[82950.38, 460988.56, 837317.88, 882000.25, 61...","[0.01, 0.04, 0.07, 0.09, 0.12, 0.14, 0.17, 0.2...","[77.2, 51.62, 54.32, 60.36, 54.42, 41.34, 41.2...",['15:1']
7,6,15:1,NaN,NaN,NaN,NaN,407.2,183,6.07,1323772.75,0.13,5.99,6.13,6.43,183184.62,"[5.99, 6.02, 6.05, 6.07, 6.1, 6.13]","[107123.71, 676337.88, 1246086.38, 1323772.75,...","[0.01, 0.04, 0.07, 0.09, 0.12, 0.14, 0.17, 0.2...","[77.2, 51.62, 54.32, 60.36, 54.42, 41.34, 41.2...",['15:1']
8,7,16:0,NaN,NaN,NaN,NaN,423.4,183,8.20,2398233.50,0.13,8.14,8.27,5.70,331869.26,"[8.14, 8.17, 8.2, 8.22, 8.25, 8.27]","[824475.56, 1900676.25, 2398233.5, 1908000.12,...","[0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.1...","[41.52, 41.4, 41.32, 41.3, 41.26, 41.26, 41.28...",['16:0']
9,8,16:1,NaN,NaN,NaN,NaN,421.4,183,6.91,1813370.88,0.13,6.86,6.99,6.40,250935.55,"[6.86, 6.88, 6.91, 6.94, 6.96, 6.99]","[831469.56, 1621372.12, 1813370.88, 1329396.75...","[0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.2...","[41.34, 47.68, 50.58, 47.64, 41.22, 41.18, 41....",['16:1']
10,9,17:0,NaN,NaN,NaN,NaN,437.4,183,9.22,547385.25,0.16,9.16,9.32,6.64,93227.77,"[9.16, 9.19, 9.22, 9.24, 9.27, 9.3, 9.32]","[248198.45, 459628.03, 547385.25, 494315.34, 4...","[0.01, 0.04, 0.06, 0.09, 0.11, 0.14, 0.17, 0.1...","[41.36, 41.34, 41.3, 41.28, 41.28, 41.26, 41.2...",['17:0']
11,10,17:1,NaN,NaN,NaN,NaN,435.4,183,7.80,2232095.75,0.16,7.72,7.88,6.41,380158.77,"[7.72, 7.75, 7.77, 7.8, 7.83, 7.85, 7.88]","[253037.59, 1193336.88, 2110146.75, 2232095.75...","[0.01, 0.04, 0.06, 0.09, 0.11, 0.14, 0.17, 0.1...","[41.36, 41.32, 41.3, 41.32, 41.32, 41.32, 41.2...",['17:1']
12,11,18:0,NaN,NaN,NaN,NaN,451.4,183,8.74,68151.45,0.16,8.69,8.85,6.30,11607.20,"[8.69, 8.72, 8.74, 8.77, 8.8, 8.82, 8.85]","[25563.86, 55750.8, 68151.45, 56380.95, 43717....","[0.01, 0.03, 0.06, 0.09, 0.11, 0.14, 0.16, 0.1...","[41.2, 41.28, 41.32, 41.34, 41.32, 41.32, 41.2...",['18:0']
13,11,18:0,NaN,NaN,NaN,NaN,451.4,183,10.21,659182.88,0.21,10.13,10.34,6.30,147352.47,"[10.13, 10.16, 10.19, 10.21, 10.24, 10.26, 10....","[111490.85, 372405.31, 613332.19, 659182.88, 5...","[0.01, 0.03, 0.06, 0.09, 0.11, 0.14, 0.16, 0.1...","[41.2, 41.28, 41.32, 41.34, 41.32, 41.32, 41.2...",['18:0']
14,12,18:1,NaN,NaN,NaN,NaN,449.4,183,8.74,4043346.75,0.16,8.69,8.85,6.21,688641.48,"[8.69, 8.72, 8.74, 8.77, 8.8, 8.82, 8.85]","[1539951.12, 3281423.5, 4043346.75, 3390620.5,...","[0.01, 0.03, 0.06, 0.09, 0.11, 0.14, 0.16, 0.1...","[41.28, 41.24, 41.28, 41.32, 41.32, 41.28, 41....",['18:1']
15,13,18:2,NaN,NaN,NaN,NaN,447.4,183,8.04,1831706.38,0.13,7.98,8.11,6.66,253472.83,"[7.98, 8.01, 8.04, 8.06, 8.09, 8.11]","[867813.12, 1648121.88, 1831706.38, 1366173.38...","[0.01, 0.03, 0.06, 0.09, 0.11, 0.14, 0.17, 0.1...","[41.28, 41.34, 41.32, 41.28, 41.24, 41.24, 41....",['18:2']
16,14,18:3,NaN,NaN,NaN,NaN,445.4,183,6.78,2320712.00,0.10,6.72,6.83,6.57,247032.14,"[6.72, 6.75, 6.78, 6.8, 6.83]","[1024367.06, 2005157.88, 2320712.0, 1686688.12...","[0.01, 0.03, 0.06, 0.09, 0.11, 0.14, 0.17, 0.1...","[41.16, 41.18, 41.22, 41.28, 41.28, 41.3, 41.2...",['18:3']
17,15,20:0,NaN,NaN,NaN,NaN,479.4,183,12.26,144204.61,0.24,12.18,12.41,6.11,36840.25,"[12.18, 12.2, 12.23, 12.26, 12.28, 12.31, 12.3...","[32783.94, 87204.47, 135666.03, 144204.61, 126...","[0.0, 0.03, 0.06, 0.08, 0.11, 0.14, 0.16, 0.19...","[41.26, 41.24, 41.2, 41.24, 41.26, 41.3, 41.26...",['20:0']
18,16,20:1,NaN,NaN,NaN,NaN,477.4,183,10.63,1023482.56,0.18,10.55,10.73,6.35,196103.42,"[10.55, 10.58, 10.6, 10.63, 10.66, 10.68, 10.7...","[176321.19, 571195.19, 940041.69, 1023482.56, ...","[0.0, 0.03, 0.06, 0.08, 0.11, 0.14, 0.16, 0.19...","[41.26, 41.28, 41.28, 41.28, 41.24, 41.24, 41....",['20:1']
19,17,20:2,NaN,NaN,NaN,NaN,475.4,183,9.32,1269626.38,0.13,9.27,9.40,5.47,175691.80,"[9.27, 9.29, 9.32, 9.34, 9.37, 9.4]","[319851.34, 880552.88, 1269626.38, 1152915.0, ...","[0.01, 0.03, 0.06, 0.08, 0.11, 0.14, 0.16, 0.1...","[41.24, 50.14, 54.24, 50.2, 41.3, 41.24, 41.22...",['20:2']
20,18,20:3,NaN,NaN,NaN,NaN,473.4,183,8.27,2384459.00,0.16,8.22,8.37,6.36,406108.47,"[8.22, 8.24, 8.27, 8.3, 8.32, 8.35, 8.37]","[968930.31, 1892715.38, 2384459.0, 2217099.75,...","[0.01, 0.03, 0.06, 0.08, 0.11, 0.14, 0.16, 0.1...","[41.32, 44.62, 46.14, 44.62, 41.3, 41.3, 41.3,...",['20:3']
21,19,20:4,NaN,NaN,NaN,NaN,471.4,183,7.61,2003592.12,0.10,7.56,7.67,6.39,213275.77,"[7.56, 7.59, 7.61, 7.64, 7.67]","[936306.81, 1807331.12, 2003592.12, 1461944.75...","[0.01, 0.03, 0.06, 0.08, 0.11, 0.14, 0.16, 0.1...","[41.24, 41.24, 41.26, 41.3, 41.3, 41.28, 41.28...",['20:4']
22,20,20:5,NaN,NaN,NaN,NaN,469.4,183,6.67,1621650.00,0.10,6.62,6.72,5.93,172619.29,"[6.62, 6.64, 6.67, 6.7, 6.72]","[416669.06, 1187179.38, 1621650.0, 1313903.12,...","[0.01, 0.03, 0.06, 0.09, 0.11, 0.14, 0.16, 0.1...","[41.16, 41.24, 41.36, 41.4, 41.38, 41.32, 41.2...",['20:5']
23,23,22:1,NaN,NaN,NaN,NaN,505.4,183,12.54,274077.97,0.24,12.46,12.70,6.50,70019.27,"[12.46, 12.49, 12.52, 12.54, 12.57, 12.59, 12....","[70879.06, 169938.95, 251977.73, 274077.97, 25...","[0.0, 0.03, 0.06, 0.08, 0.11, 0.13, 0.16, 0.19...","[41.38, 41.34, 41.32, 41.32, 41.32, 41.28, 41....",['22:1']
24,24,22:2,NaN,NaN,NaN,NaN,503.4,183,11.18,436034.28,0.18,11.13,11.31,6.13,83545.94,"[11.13, 11.15, 11.18, 11.2, 11.23, 11.26, 11.2...","[180782.12, 350797.94, 436034.28, 399022.06, 3...","[0.0, 0.03, 0.06, 0.08, 0.11, 0.13, 0.16, 0.19...","[41.22, 41.28, 41.28, 41.26, 41.24, 41.24, 41....",['22:2']
25,25,22:6,NaN,NaN,NaN,NaN,495.4,183,7.56,2139167.75,0.10,7.51,7.61,5.89,227707.35,"[7.51, 7.53, 7.56, 7.58, 7.61]","[582223.0, 1613261.25, 2139167.75, 1702252.88,...","[0.0, 0.03, 0.06, 0.08, 0.11, 0.13, 0.16, 0.19...","[41.26, 41.26, 41.26, 41.26, 41.24, 41.28, 41....",['22:6']
26,28,24:1,NaN,NaN,NaN,NaN,533.4,183,14.53,55693.80,0.29,14.43,14.72,7.73,17192.42,"[14.43, 14.46, 14.48, 14.51, 14.53, 14.56, 14....","[26937.22, 39944.06, 49765.92, 55172.4, 55693....","[0.0, 0.03, 0.05, 0.08, 0.11, 0.13, 0.16, 0.18...","[41.36, 41.3, 41.3, 41.3, 41.32, 41.28, 41.26,...",['24:1']
27,32,d2-16:0,NaN,NaN,NaN,NaN,425.4,183,8.17,208040.61,0.13,8.12,8.25,5.45,28788.81,"[8.12, 8.14, 8.17, 8.2, 8.22, 8.25]","[26078.16, 125422.11, 208040.61, 200464.86, 12...","[0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.1...","[41.3, 41.3, 41.32, 41.38, 41.38, 41.3, 41.22,...",['16:0']

In [50]:
OzON_df

,Group_Sample,Lipid,Biology,Genotype,Cage,Mouse,Parent_Ion,Product_Ion,Peak_Retention_Time,Peak_Height,FWHM,Start,Stop,Peak_Width,Peak_Area,Peak_Data_Retention_Times,Peak_Data_Intensities,Full_Data_Retention_Times,Full_Data_Intensities,FAC
0,0,"10:0 / 18:2 (9Z,12Z)n-6,n-9 / 14:1 (9Z)n-5 / 1...",NaN,NaN,NaN,NaN,339.3,183,4.06,286286.12,0.10,4.01,4.11,4.67,31977.61,"[4.01, 4.03, 4.06, 4.09, 4.11]","[200.56, 157366.09, 286286.12, 256789.27, 8633...","[0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.2, 41.24, 41.28, 41.32, 41.3, 41.34, 41.32...","['10:0', '18:2', '14:1', '18:3', '16:1', '18:1']"
1,0,"10:0 / 18:2 (9Z,12Z)n-6,n-9 / 14:1 (9Z)n-5 / 1...",NaN,NaN,NaN,NaN,339.3,183,6.92,289018.91,0.13,6.87,7.00,5.86,40353.57,"[6.87, 6.89, 6.92, 6.95, 6.97, 7.0]","[63443.45, 195564.33, 289018.91, 261424.59, 17...","[0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.2, 41.24, 41.28, 41.32, 41.3, 41.34, 41.32...","['10:0', '18:2', '14:1', '18:3', '16:1', '18:1']"
2,0,"10:0 / 18:2 (9Z,12Z)n-6,n-9 / 14:1 (9Z)n-5 / 1...",NaN,NaN,NaN,NaN,339.3,183,8.76,816327.25,0.16,8.70,8.86,5.87,136787.75,"[8.7, 8.73, 8.76, 8.78, 8.81, 8.83, 8.86]","[188222.31, 552963.0, 816327.25, 779636.62, 61...","[0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.2, 41.24, 41.28, 41.32, 41.3, 41.34, 41.32...","['10:0', '18:2', '14:1', '18:3', '16:1', '18:1']"
3,1,11:0 / 15:1 (10Z)n-5 / 17:1 (10Z)n-7,NaN,NaN,NaN,NaN,353.3,183,4.37,231466.78,0.10,4.32,4.43,5.72,25850.29,"[4.32, 4.35, 4.37, 4.4, 4.43]","[57376.54, 174686.19, 231466.78, 170080.52, 77...","[0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.3, 41.3, 41.3, 41.3, 41.26, 41.28, 41.3, 4...","['11:0', '15:1', '17:1']"
4,1,11:0 / 15:1 (10Z)n-5 / 17:1 (10Z)n-7,NaN,NaN,NaN,NaN,353.3,183,6.08,189818.09,0.13,6.03,6.16,5.95,26499.53,"[6.03, 6.05, 6.08, 6.11, 6.13, 6.16]","[46655.46, 136257.05, 189818.09, 162114.73, 10...","[0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.3, 41.3, 41.3, 41.3, 41.26, 41.28, 41.3, 4...","['11:0', '15:1', '17:1']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,42,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6,n-9,n-12,n-15",NaN,NaN,NaN,NaN,309.1,183,7.58,165001.75,0.13,7.52,7.66,5.74,23037.97,"[7.52, 7.55, 7.58, 7.6, 7.63, 7.66]","[36798.7, 115778.87, 165001.75, 140199.56, 856...","[0.02, 0.05, 0.07, 0.1, 0.13, 0.15, 0.18, 0.21...","[41.24, 41.3, 41.36, 41.34, 41.3, 41.24, 47.94...",['22:6']
59,43,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6,n-9,n-12,n...",NaN,NaN,NaN,NaN,269.1,183,7.58,64931.14,0.13,7.53,7.66,5.82,9065.85,"[7.53, 7.55, 7.58, 7.61, 7.63, 7.66]","[14548.56, 44982.9, 64931.14, 54201.54, 32713....","[0.02, 0.05, 0.08, 0.1, 0.13, 0.16, 0.18, 0.21...","[41.24, 41.3, 41.26, 41.24, 41.28, 41.32, 41.2...","['22:6', '12:1', '13:1', '14:1', '15:1', '16:1..."
60,48,"6:0 / 20:5 (5Z,8Z,11Z,14Z,17Z)n-3,n-6,n-9,n-12...",NaN,NaN,NaN,NaN,283.1,183,7.63,91986.47,0.10,7.58,7.68,6.27,10274.71,"[7.58, 7.6, 7.63, 7.66, 7.68]","[36613.4, 77269.47, 91986.47, 70263.1, 44811.46]","[0.02, 0.05, 0.08, 0.1, 0.13, 0.15, 0.18, 0.21...","[41.26, 41.22, 41.24, 41.26, 41.22, 41.24, 41....","['6:0', '20:5', '20:4', '12:1', '13:1', '14:1'..."
61,48,"6:0 / 20:5 (5Z,8Z,11Z,14Z,17Z)n-3,n-6,n-9,n-12...",NaN,NaN,NaN,NaN,283.1,183,7.63,105181.59,0.13,7.58,7.71,6.32,14685.73,"[7.58, 7.6, 7.63, 7.66, 7.68, 7.71]","[41418.8, 88710.27, 105181.59, 80809.47, 53218...","[0.02, 0.05, 0.08, 0.1, 0.13, 0.15, 0.18, 0.21...","[41.26, 41.22, 41.24, 41.26, 41.22, 41.24, 41....","['6:0', '20:5', '20:4', '12:1', '13:1', '14:1'..."
62,50,d2-16:0,NaN,NaN,NaN,NaN,425.4,183,8.20,207300.47,0.13,8.14,8.27,5.54,28943.83,"[8.14, 8.17, 8.2, 8.22, 8.25, 8.27]","[34764.2, 132859.47, 207300.47, 192313.89, 124...","[0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.1...","[41.3, 41.28, 41.3, 41.3, 41.3, 41.3, 41.3, 41...",['16:0']

# FIND MATHCES BETWEEN OZON AND OZOFF DF

In [62]:
import pandas as pd

# Example DataFrames
# Assuming these DataFrames are already defined:
# OzON_df and OzOFF_df with columns including 'FAC' and 'Peak_Retention_Time'

def find_matches(OzON_df, OzOFF_df, rt_tolerance=0.5):
    # Prepare the output DataFrame with additional columns for match details
    matched_columns = list(OzON_df.columns) + ['OzOFF_Match', 'OFF_RT']
    df_matched = pd.DataFrame(columns=matched_columns)

    # Iterate through each row in the OzON DataFrame
    for index, ozon_row in OzON_df.iterrows():
        on_fac_list = ozon_row['FAC']
        on_rt = ozon_row['Peak_Retention_Time']

        # Check each row in the OzOFF DataFrame for potential FAC matches
        for _, ozoff_row in OzOFF_df.iterrows():
            off_fac_list = ozoff_row['FAC']
            off_rt = ozoff_row['Peak_Retention_Time']

            # Check for any common FAC entries and within the retention time tolerance
            if any(fac in off_fac_list for fac in on_fac_list) and abs(on_rt - off_rt) <= rt_tolerance:
                # Create a new row for the matched DataFrame including additional match details
                match_data = ozon_row.to_dict()
                match_data['OzOFF_Match'] = off_fac_list
                match_data['OFF_RT'] = off_rt
                df_matched = df_matched.append(match_data, ignore_index=True)

    return df_matched

# Usage
df_matched = find_matches(OzON_df, OzOFF_df)
df_matched

,Group_Sample,Lipid,Biology,Genotype,Cage,Mouse,Parent_Ion,Product_Ion,Peak_Retention_Time,Peak_Height,...,Stop,Peak_Width,Peak_Area,Peak_Data_Retention_Times,Peak_Data_Intensities,Full_Data_Retention_Times,Full_Data_Intensities,FAC,OzOFF_Match,OFF_RT
0,0,"10:0 / 18:2 (9Z,12Z)n-6,n-9 / 14:1 (9Z)n-5 / 1...",NaN,NaN,NaN,NaN,339.3,183,4.06,286286.12,...,4.11,4.67,31977.61,"[4.01, 4.03, 4.06, 4.09, 4.11]","[200.56, 157366.09, 286286.12, 256789.27, 8633...","[0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.2, 41.24, 41.28, 41.32, 41.3, 41.34, 41.32...","['10:0', '18:2', '14:1', '18:3', '16:1', '18:1']",['11:0'],4.37
1,0,"10:0 / 18:2 (9Z,12Z)n-6,n-9 / 14:1 (9Z)n-5 / 1...",NaN,NaN,NaN,NaN,339.3,183,6.92,289018.91,...,7.00,5.86,40353.57,"[6.87, 6.89, 6.92, 6.95, 6.97, 7.0]","[63443.45, 195564.33, 289018.91, 261424.59, 17...","[0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.2, 41.24, 41.28, 41.32, 41.3, 41.34, 41.32...","['10:0', '18:2', '14:1', '18:3', '16:1', '18:1']",['15:0'],7.28
2,0,"10:0 / 18:2 (9Z,12Z)n-6,n-9 / 14:1 (9Z)n-5 / 1...",NaN,NaN,NaN,NaN,339.3,183,6.92,289018.91,...,7.00,5.86,40353.57,"[6.87, 6.89, 6.92, 6.95, 6.97, 7.0]","[63443.45, 195564.33, 289018.91, 261424.59, 17...","[0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.2, 41.24, 41.28, 41.32, 41.3, 41.34, 41.32...","['10:0', '18:2', '14:1', '18:3', '16:1', '18:1']",['16:1'],6.91
3,0,"10:0 / 18:2 (9Z,12Z)n-6,n-9 / 14:1 (9Z)n-5 / 1...",NaN,NaN,NaN,NaN,339.3,183,6.92,289018.91,...,7.00,5.86,40353.57,"[6.87, 6.89, 6.92, 6.95, 6.97, 7.0]","[63443.45, 195564.33, 289018.91, 261424.59, 17...","[0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.2, 41.24, 41.28, 41.32, 41.3, 41.34, 41.32...","['10:0', '18:2', '14:1', '18:3', '16:1', '18:1']",['18:3'],6.78
4,0,"10:0 / 18:2 (9Z,12Z)n-6,n-9 / 14:1 (9Z)n-5 / 1...",NaN,NaN,NaN,NaN,339.3,183,6.92,289018.91,...,7.00,5.86,40353.57,"[6.87, 6.89, 6.92, 6.95, 6.97, 7.0]","[63443.45, 195564.33, 289018.91, 261424.59, 17...","[0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.2, 41.24, 41.28, 41.32, 41.3, 41.34, 41.32...","['10:0', '18:2', '14:1', '18:3', '16:1', '18:1']",['20:5'],6.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,50,d2-16:0,NaN,NaN,NaN,NaN,425.4,183,8.20,207300.47,...,8.27,5.54,28943.83,"[8.14, 8.17, 8.2, 8.22, 8.25, 8.27]","[34764.2, 132859.47, 207300.47, 192313.89, 124...","[0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.1...","[41.3, 41.28, 41.3, 41.3, 41.3, 41.3, 41.3, 41...",['16:0'],['16:0'],8.20
239,50,d2-16:0,NaN,NaN,NaN,NaN,425.4,183,8.20,207300.47,...,8.27,5.54,28943.83,"[8.14, 8.17, 8.2, 8.22, 8.25, 8.27]","[34764.2, 132859.47, 207300.47, 192313.89, 124...","[0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.1...","[41.3, 41.28, 41.3, 41.3, 41.3, 41.3, 41.3, 41...",['16:0'],['17:1'],7.80
240,50,d2-16:0,NaN,NaN,NaN,NaN,425.4,183,8.20,207300.47,...,8.27,5.54,28943.83,"[8.14, 8.17, 8.2, 8.22, 8.25, 8.27]","[34764.2, 132859.47, 207300.47, 192313.89, 124...","[0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.1...","[41.3, 41.28, 41.3, 41.3, 41.3, 41.3, 41.3, 41...",['16:0'],['18:2'],8.04
241,50,d2-16:0,NaN,NaN,NaN,NaN,425.4,183,8.20,207300.47,...,8.27,5.54,28943.83,"[8.14, 8.17, 8.2, 8.22, 8.25, 8.27]","[34764.2, 132859.47, 207300.47, 192313.89, 124...","[0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.1...","[41.3, 41.28, 41.3, 41.3, 41.3, 41.3, 41.3, 41...",['16:0'],['20:3'],8.27
242,50,d2-16:0,NaN,NaN,NaN,NaN,425.4,183,8.20,207300.47,...,8.27,5.54,28943.83,"[8.14, 8.17, 8.2, 8.22, 8.25, 8.27]","[34764.2, 132859.47, 207300.47, 192313.89, 124...","[0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.1...","[41.3, 41.28, 41.3, 41.3, 41.3, 41.3, 41.3, 41...",['16:0'],['16:0'],8.17

# Remove OzON with ##:0

In [70]:
def contains_colon_zero(fac_string):
    return ':0' not in fac_string  # Return True only if ':0' is not found

# Apply the filter to exclude strings containing ':0'
df_filtered = df_matched[df_matched['OzOFF_Match'].apply(contains_colon_zero)]

df_filtered

,Group_Sample,Lipid,Biology,Genotype,Cage,Mouse,Parent_Ion,Product_Ion,Peak_Retention_Time,Peak_Height,...,Stop,Peak_Width,Peak_Area,Peak_Data_Retention_Times,Peak_Data_Intensities,Full_Data_Retention_Times,Full_Data_Intensities,FAC,OzOFF_Match,OFF_RT
2,0,"10:0 / 18:2 (9Z,12Z)n-6,n-9 / 14:1 (9Z)n-5 / 1...",NaN,NaN,NaN,NaN,339.3,183,6.92,289018.91,...,7.00,5.86,40353.57,"[6.87, 6.89, 6.92, 6.95, 6.97, 7.0]","[63443.45, 195564.33, 289018.91, 261424.59, 17...","[0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.2, 41.24, 41.28, 41.32, 41.3, 41.34, 41.32...","['10:0', '18:2', '14:1', '18:3', '16:1', '18:1']",['16:1'],6.91
3,0,"10:0 / 18:2 (9Z,12Z)n-6,n-9 / 14:1 (9Z)n-5 / 1...",NaN,NaN,NaN,NaN,339.3,183,6.92,289018.91,...,7.00,5.86,40353.57,"[6.87, 6.89, 6.92, 6.95, 6.97, 7.0]","[63443.45, 195564.33, 289018.91, 261424.59, 17...","[0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.2, 41.24, 41.28, 41.32, 41.3, 41.34, 41.32...","['10:0', '18:2', '14:1', '18:3', '16:1', '18:1']",['18:3'],6.78
4,0,"10:0 / 18:2 (9Z,12Z)n-6,n-9 / 14:1 (9Z)n-5 / 1...",NaN,NaN,NaN,NaN,339.3,183,6.92,289018.91,...,7.00,5.86,40353.57,"[6.87, 6.89, 6.92, 6.95, 6.97, 7.0]","[63443.45, 195564.33, 289018.91, 261424.59, 17...","[0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.2, 41.24, 41.28, 41.32, 41.3, 41.34, 41.32...","['10:0', '18:2', '14:1', '18:3', '16:1', '18:1']",['20:5'],6.67
7,0,"10:0 / 18:2 (9Z,12Z)n-6,n-9 / 14:1 (9Z)n-5 / 1...",NaN,NaN,NaN,NaN,339.3,183,8.76,816327.25,...,8.86,5.87,136787.75,"[8.7, 8.73, 8.76, 8.78, 8.81, 8.83, 8.86]","[188222.31, 552963.0, 816327.25, 779636.62, 61...","[0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.2, 41.24, 41.28, 41.32, 41.3, 41.34, 41.32...","['10:0', '18:2', '14:1', '18:3', '16:1', '18:1']",['18:1'],8.74
8,0,"10:0 / 18:2 (9Z,12Z)n-6,n-9 / 14:1 (9Z)n-5 / 1...",NaN,NaN,NaN,NaN,339.3,183,8.76,816327.25,...,8.86,5.87,136787.75,"[8.7, 8.73, 8.76, 8.78, 8.81, 8.83, 8.86]","[188222.31, 552963.0, 816327.25, 779636.62, 61...","[0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.2, 41.24, 41.28, 41.32, 41.3, 41.34, 41.32...","['10:0', '18:2', '14:1', '18:3', '16:1', '18:1']",['20:3'],8.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,48,"6:0 / 20:5 (5Z,8Z,11Z,14Z,17Z)n-3,n-6,n-9,n-12...",NaN,NaN,NaN,NaN,283.1,183,7.63,105181.59,...,7.71,6.32,14685.73,"[7.58, 7.6, 7.63, 7.66, 7.68, 7.71]","[41418.8, 88710.27, 105181.59, 80809.47, 53218...","[0.02, 0.05, 0.08, 0.1, 0.13, 0.15, 0.18, 0.21...","[41.26, 41.22, 41.24, 41.26, 41.22, 41.24, 41....","['6:0', '20:5', '20:4', '12:1', '13:1', '14:1'...",['20:4'],7.61
237,48,"6:0 / 20:5 (5Z,8Z,11Z,14Z,17Z)n-3,n-6,n-9,n-12...",NaN,NaN,NaN,NaN,283.1,183,7.63,105181.59,...,7.71,6.32,14685.73,"[7.58, 7.6, 7.63, 7.66, 7.68, 7.71]","[41418.8, 88710.27, 105181.59, 80809.47, 53218...","[0.02, 0.05, 0.08, 0.1, 0.13, 0.15, 0.18, 0.21...","[41.26, 41.22, 41.24, 41.26, 41.22, 41.24, 41....","['6:0', '20:5', '20:4', '12:1', '13:1', '14:1'...",['22:6'],7.56
239,50,d2-16:0,NaN,NaN,NaN,NaN,425.4,183,8.20,207300.47,...,8.27,5.54,28943.83,"[8.14, 8.17, 8.2, 8.22, 8.25, 8.27]","[34764.2, 132859.47, 207300.47, 192313.89, 124...","[0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.1...","[41.3, 41.28, 41.3, 41.3, 41.3, 41.3, 41.3, 41...",['16:0'],['17:1'],7.80
240,50,d2-16:0,NaN,NaN,NaN,NaN,425.4,183,8.20,207300.47,...,8.27,5.54,28943.83,"[8.14, 8.17, 8.2, 8.22, 8.25, 8.27]","[34764.2, 132859.47, 207300.47, 192313.89, 124...","[0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.1...","[41.3, 41.28, 41.3, 41.3, 41.3, 41.3, 41.3, 41...",['16:0'],['18:2'],8.04
241,50,d2-16:0,NaN,NaN,NaN,NaN,425.4,183,8.20,207300.47,...,8.27,5.54,28943.83,"[8.14, 8.17, 8.2, 8.22, 8.25, 8.27]","[34764.2, 132859.47, 207300.47, 192313.89, 124...","[0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.1...","[41.3, 41.28, 41.3, 41.3, 41.3, 41.3, 41.3, 41...",['16:0'],['20:3'],8.27

# MATCH FAC TO OzOFF Match

In [99]:
import pandas as pd

# Assuming you have a DataFrame named 'df_filtered' with columns 'FAC' and 'OzOFF_Match'

# Convert the 'OzOFF_Match' column to a list if it's a string
df_filtered['OzOFF_Match'] = df_filtered['OzOFF_Match'].apply(lambda x: [x] if isinstance(x, str) else x)

# Apply the isin() function to check if elements from OzOFF_Match exist in FAC
df_filtered['Match'] = df_filtered.apply(lambda row: any(item in row['FAC'] for item in row['OzOFF_Match']), axis=1)

# Filter the DataFrame to keep only rows with a match
df_filtered_correctly = df_filtered[df_filtered['Match']]

# Drop the 'Match' column since it's no longer needed
df_filtered_correctly = df_filtered_correctly.drop(columns=['Match'])

# Print the filtered DataFrame to verify the results
print("Filtered DataFrame:")
print(df_filtered_correctly)

Filtered DataFrame:
    Group_Sample                                              Lipid  Biology  \
45             5                                           14:1(9Z)      NaN
58             8                                               16:1      NaN
81            12                                               18:1      NaN
102           15                                               18:3      NaN
107           16                               18:3 (6Z,9Z,12Z))n-6      NaN
112           17                           18:3 (6Z,9Z,12Z))n-6,n-9      NaN
121           19                              18:3 (9Z,12Z,15Z))n-3      NaN
126           21                                               20:1      NaN
128           22                                               20:2      NaN
143           24                                               20:3      NaN
149           25                               20:3 (8Z,11Z,14Z)n-6      NaN
155           26                           20:3 (8Z,11Z,14Z)n-6,n-9      NaN
166           28                                               20:4      NaN
181           31                        20:5 (5Z,8Z,11Z,14Z,17Z)n-3      NaN
188           35                                               22:1      NaN
189           36                                               22:2      NaN
194           37                                               22:6      NaN
204           39                22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6      NaN
212           40            22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6,n-9      NaN
217           41       22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6,n-9,n-12      NaN
222           42  22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6,n-9,n-12,n-15      NaN

     Genotype  Cage  Mouse  Parent_Ion Product_Ion  Peak_Retention_Time  \
45        NaN   NaN    NaN       393.4         183                 5.31
58        NaN   NaN    NaN       421.4         183                 6.94
81        NaN   NaN    NaN       449.4         183                 8.77
102       NaN   NaN    NaN       445.4         183                 6.80
107       NaN   NaN    NaN       377.2         183                 6.79
112       NaN   NaN    NaN       337.2         183                 6.79
121       NaN   NaN    NaN       419.3         183                 6.62
126       NaN   NaN    NaN       477.4         183                10.66
128       NaN   NaN    NaN       475.4         183                 9.34
143       NaN   NaN    NaN       473.4         183                 8.30
149       NaN   NaN    NaN       405.2         183                 8.30
155       NaN   NaN    NaN       365.2         183                 8.31
166       NaN   NaN    NaN       471.4         183                 7.64
181       NaN   NaN    NaN       443.3         183                 6.70
188       NaN   NaN    NaN       505.4         183                12.57
189       NaN   NaN    NaN       503.4         183                11.20
194       NaN   NaN    NaN       495.4         183                 7.58
204       NaN   NaN    NaN       429.2         183                 7.59
212       NaN   NaN    NaN       389.3         183                 7.57
217       NaN   NaN    NaN       349.2         183                 7.57
222       NaN   NaN    NaN       309.1         183                 7.58

     Peak_Height  ...   Stop  Peak_Width  Peak_Area  \
45     485171.69  ...   5.39        6.00   67740.93
58    1018232.88  ...   7.02        6.56  170601.97
81    2367621.25  ...   8.85        6.20  330573.41
102    710432.44  ...   6.86        6.48   99192.42
107    248708.52  ...   6.86        5.97   34725.33
112    180696.58  ...   6.87        5.94   25229.32
121    172950.81  ...   6.68        6.60   24147.84
126    625269.31  ...  10.76        6.39  122222.41
128    480600.69  ...   9.42        5.51   67102.71
143    690766.69  ...   8.40        6.47  115735.96
149    211912.97  ...   8.38        6.11   29587.84
155    188855.77  ...   8.39        6.10   26368.53
166    480694.47  ...   7.69        6.73   67115.81
181    110158.11  ...   6.75        6.11   12304.45
188    155917.52  ...  12.73        6.43   39185.29
189    164623.83  ...  11.34        6.11   32176.37
194    314451.75  ...   7.64        6.05   35123.65
204     92015.65  ...   7.64        6.42   12847.46
212    160292.03  ...   7.65        5.82   22380.39
217    216939.06  ...   7.65        5.85   30289.59
222    165001.75  ...   7.66        5.74   23037.97

                             Peak_Data_Retention_Times  \
45                [5.26, 5.29, 5.31, 5.34, 5.37, 5.39]
58          [6.86, 6.88, 6.91, 6.94, 6.96, 6.99, 7.02]
81                 [8.72, 8.74, 8.77, 8.8, 8.82, 8.85]
102                [6.72, 6.75, 6.78, 6.8, 6.83, 6.86]
107               [6.73, 6.76, 6.79, 6.81, 6.84, 6.86]
112               [6.74, 6.76, 6.79, 6.81, 6.84, 6.87]
121                [6.54, 6.57, 6.6, 6.62, 6.65, 6.68]
126  [10.58, 10.6, 10.63, 10.66, 10.68, 10.71, 10.7...
128                [9.29, 9.32, 9.34, 9.37, 9.4, 9.42]
143           [8.24, 8.27, 8.3, 8.32, 8.35, 8.37, 8.4]
149                [8.25, 8.28, 8.3, 8.33, 8.36, 8.38]
155               [8.26, 8.28, 8.31, 8.33, 8.36, 8.39]
166               [7.56, 7.59, 7.61, 7.64, 7.67, 7.69]
181                      [6.65, 6.67, 6.7, 6.72, 6.75]
188  [12.49, 12.52, 12.54, 12.57, 12.59, 12.62, 12....
189  [11.15, 11.18, 11.2, 11.23, 11.26, 11.28, 11.3...
194                     [7.53, 7.56, 7.58, 7.61, 7.64]
204               [7.51, 7.54, 7.57, 7.59, 7.62, 7.64]
212                [7.52, 7.54, 7.57, 7.6, 7.62, 7.65]
217                [7.52, 7.55, 7.57, 7.6, 7.63, 7.65]
222                [7.52, 7.55, 7.58, 7.6, 7.63, 7.66]

                                 Peak_Data_Intensities  \
45   [98226.66, 329124.66, 485171.69, 430486.72, 27...
58   [117966.47, 557275.0, 975599.94, 1018232.88, 7...
81   [997458.25, 2008520.12, 2367621.25, 1918496.5,...
102  [120488.8, 365312.91, 653753.94, 710432.44, 49...
107  [43745.56, 160864.81, 248708.52, 231787.06, 15...
112  [39360.04, 124923.77, 180696.58, 159095.52, 10...
121  [19838.68, 99693.97, 171789.39, 172950.81, 115...
126  [110585.83, 348636.66, 571846.94, 625269.31, 5...
128  [118275.3, 328070.66, 480600.69, 445589.56, 32...
143  [310500.88, 572488.25, 690766.69, 628126.38, 4...
149  [54999.18, 145898.62, 211912.97, 199323.78, 14...
155  [61749.06, 143097.17, 188855.77, 165823.98, 11...
166  [72657.73, 282868.03, 474743.5, 480694.47, 339...
181  [42310.22, 93655.2, 110158.11, 78164.97, 46428...
188  [34821.66, 88315.87, 138324.44, 155917.52, 147...
189  [72616.62, 137573.41, 164623.83, 149136.81, 12...
194  [110649.33, 257549.17, 314451.75, 232477.31, 1...
204  [7189.16, 46100.68, 87015.15, 92015.65, 60886....
212  [23035.5, 97191.2, 160292.03, 156165.69, 10207...
217  [41436.7, 145455.84, 216939.06, 191392.55, 120...
222  [36798.7, 115778.87, 165001.75, 140199.56, 856...

                             Full_Data_Retention_Times  \
45   [0.02, 0.04, 0.07, 0.09, 0.12, 0.15, 0.17, 0.2...
58   [0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.2...
81   [0.01, 0.03, 0.06, 0.09, 0.11, 0.14, 0.16, 0.1...
102  [0.01, 0.03, 0.06, 0.09, 0.11, 0.14, 0.17, 0.1...
107  [0.02, 0.04, 0.07, 0.1, 0.12, 0.15, 0.17, 0.2,...
112  [0.02, 0.05, 0.07, 0.1, 0.13, 0.15, 0.18, 0.2,...
121  [0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.2...
126  [0.0, 0.03, 0.06, 0.08, 0.11, 0.14, 0.16, 0.19...
128  [0.01, 0.03, 0.06, 0.08, 0.11, 0.14, 0.16, 0.1...
143  [0.01, 0.03, 0.06, 0.08, 0.11, 0.14, 0.16, 0.1...
149  [0.01, 0.04, 0.07, 0.09, 0.12, 0.15, 0.17, 0.2...
155  [0.02, 0.04, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...
166  [0.01, 0.03, 0.06, 0.08, 0.11, 0.14, 0.16, 0.1...
181  [0.01, 0.04, 0.06, 0.09, 0.11, 0.14, 0.17, 0.1...
188  [0.0, 0.03, 0.06, 0.08, 0.11, 0.13, 0.16, 0.19...
189  [0.0, 0.03, 0.06, 0.08, 0.11, 0.13, 0.16, 0.19...
194  [0.0, 0.03, 0.06, 0.08, 0.11, 0.13, 0.16, 0.19...
204  [0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.1...
212  [0.02, 0.04, 0.07, 0.09, 0.12, 0.15, 0.17, 0.2...
217  [0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...
222  [0.02, 0.05, 0.07, 0.1, 0.13, 0.15, 0.18, 0.21...

                                 Full_Data_Intensities       FAC OzOFF_Match  \
45   [41.42, 41.3, 41.3, 41.36, 41.4, 41.32, 41.26,...  ['14:1']  [['14:1']]
58   [41.22, 41.24, 41.3, 41.32, 41.32, 41.26, 41.2...  ['16:1']  [['16:1']]
81   [41.36, 41.34, 41.34, 41.36, 41.34, 41.3, 41.2...  ['18:1']  [['18:1']]
102  [41.14, 41.28, 41.3, 41.28, 41.28, 41.34, 41.3...  ['18:3']  [['18:3']]
107  [41.22, 41.28, 41.26, 41.28, 41.3, 41.34, 41.3...  ['18:3']  [['18:3']]
112  [73.38, 50.56, 44.98, 61.66, 74.36, 74.2, 77.8...  ['18:3']  [['18:3']]
121  [41.28, 41.28, 41.28, 41.3, 41.28, 41.3, 41.3,...  ['18:3']  [['18:3']]
126  [41.28, 41.28, 41.28, 41.28, 41.28, 41.26, 41....  ['20:1']  [['20:1']]
128  [41.34, 41.34, 41.34, 41.3, 41.28, 41.28, 41.3...  ['20:2']  [['20:2']]
143  [41.22, 41.24, 41.28, 41.34, 41.36, 41.32, 41....  ['20:3']  [['20:3']]
149  [41.32, 41.28, 41.32, 41.4, 41.34, 41.3, 41.3,...  ['20:3']  [['20:3']]
155  [41.38, 41.34, 41.32, 41.32, 42.48, 42.96, 42....  ['20:3']  [['20:3']]
166  [41.24, 41.22, 41.28, 41.34, 41.34, 41.32, 41....  ['20:4']  [['20:4']]
181  [41.3, 41.3, 41.32, 41.32, 41.32, 41.28, 41.26...  ['20:5']  [['20:5']]
188  [41.2, 41.24, 41.26, 41.22, 41.3, 41.34, 41.34...  ['22:1']  [['22:1']]
189  [41.26, 41.28, 41.32, 41.32, 41.32, 41.32, 41....  ['22:2']  [['22:2']]
194  [41.18, 41.18, 41.24, 41.28, 41.26, 41.28, 41....  ['22:6']  [['22:6']]
204  [41.34, 43.38, 44.32, 43.36, 41.32, 41.26, 41....  ['22:6']  [['22:6']]
212  [41.2, 41.26, 41.32, 41.3, 41.3, 41.3, 41.3, 4...  ['22:6']  [['22:6']]
217  [41.14, 41.3, 41.34, 41.32, 41.32, 41.34, 41.3...  ['22:6']  [['22:6']]
222  [41.24, 41.3, 41.36, 41.34, 41.3, 41.24, 47.94...  ['22:6']  [['22:6']]

    OFF_RT
45    5.31
58    6.91
81    8.74
102   6.78
107   6.78
112   6.78
121   6.78
126  10.63
128   9.32
143   8.27
149   8.27
155   8.27
166   7.61
181   6.67
188  12.54
189  11.18
194   7.56
204   7.56
212   7.56
217   7.56
222   7.56

[21 rows x 22 columns]

/home/iyer95/.conda/envs/CLA/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/iyer95/.conda/envs/CLA/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == "__main__":

In [100]:
df_filtered_correctly

,Group_Sample,Lipid,Biology,Genotype,Cage,Mouse,Parent_Ion,Product_Ion,Peak_Retention_Time,Peak_Height,...,Stop,Peak_Width,Peak_Area,Peak_Data_Retention_Times,Peak_Data_Intensities,Full_Data_Retention_Times,Full_Data_Intensities,FAC,OzOFF_Match,OFF_RT
45,5,14:1(9Z),NaN,NaN,NaN,NaN,393.4,183,5.31,485171.69,...,5.39,6.00,67740.93,"[5.26, 5.29, 5.31, 5.34, 5.37, 5.39]","[98226.66, 329124.66, 485171.69, 430486.72, 27...","[0.02, 0.04, 0.07, 0.09, 0.12, 0.15, 0.17, 0.2...","[41.42, 41.3, 41.3, 41.36, 41.4, 41.32, 41.26,...",['14:1'],[['14:1']],5.31
58,8,16:1,NaN,NaN,NaN,NaN,421.4,183,6.94,1018232.88,...,7.02,6.56,170601.97,"[6.86, 6.88, 6.91, 6.94, 6.96, 6.99, 7.02]","[117966.47, 557275.0, 975599.94, 1018232.88, 7...","[0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.2...","[41.22, 41.24, 41.3, 41.32, 41.32, 41.26, 41.2...",['16:1'],[['16:1']],6.91
81,12,18:1,NaN,NaN,NaN,NaN,449.4,183,8.77,2367621.25,...,8.85,6.20,330573.41,"[8.72, 8.74, 8.77, 8.8, 8.82, 8.85]","[997458.25, 2008520.12, 2367621.25, 1918496.5,...","[0.01, 0.03, 0.06, 0.09, 0.11, 0.14, 0.16, 0.1...","[41.36, 41.34, 41.34, 41.36, 41.34, 41.3, 41.2...",['18:1'],[['18:1']],8.74
102,15,18:3,NaN,NaN,NaN,NaN,445.4,183,6.80,710432.44,...,6.86,6.48,99192.42,"[6.72, 6.75, 6.78, 6.8, 6.83, 6.86]","[120488.8, 365312.91, 653753.94, 710432.44, 49...","[0.01, 0.03, 0.06, 0.09, 0.11, 0.14, 0.17, 0.1...","[41.14, 41.28, 41.3, 41.28, 41.28, 41.34, 41.3...",['18:3'],[['18:3']],6.78
107,16,"18:3 (6Z,9Z,12Z))n-6",NaN,NaN,NaN,NaN,377.2,183,6.79,248708.52,...,6.86,5.97,34725.33,"[6.73, 6.76, 6.79, 6.81, 6.84, 6.86]","[43745.56, 160864.81, 248708.52, 231787.06, 15...","[0.02, 0.04, 0.07, 0.1, 0.12, 0.15, 0.17, 0.2,...","[41.22, 41.28, 41.26, 41.28, 41.3, 41.34, 41.3...",['18:3'],[['18:3']],6.78
112,17,"18:3 (6Z,9Z,12Z))n-6,n-9",NaN,NaN,NaN,NaN,337.2,183,6.79,180696.58,...,6.87,5.94,25229.32,"[6.74, 6.76, 6.79, 6.81, 6.84, 6.87]","[39360.04, 124923.77, 180696.58, 159095.52, 10...","[0.02, 0.05, 0.07, 0.1, 0.13, 0.15, 0.18, 0.2,...","[73.38, 50.56, 44.98, 61.66, 74.36, 74.2, 77.8...",['18:3'],[['18:3']],6.78
121,19,"18:3 (9Z,12Z,15Z))n-3",NaN,NaN,NaN,NaN,419.3,183,6.62,172950.81,...,6.68,6.60,24147.84,"[6.54, 6.57, 6.6, 6.62, 6.65, 6.68]","[19838.68, 99693.97, 171789.39, 172950.81, 115...","[0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.2...","[41.28, 41.28, 41.28, 41.3, 41.28, 41.3, 41.3,...",['18:3'],[['18:3']],6.78
126,21,20:1,NaN,NaN,NaN,NaN,477.4,183,10.66,625269.31,...,10.76,6.39,122222.41,"[10.58, 10.6, 10.63, 10.66, 10.68, 10.71, 10.7...","[110585.83, 348636.66, 571846.94, 625269.31, 5...","[0.0, 0.03, 0.06, 0.08, 0.11, 0.14, 0.16, 0.19...","[41.28, 41.28, 41.28, 41.28, 41.28, 41.26, 41....",['20:1'],[['20:1']],10.63
128,22,20:2,NaN,NaN,NaN,NaN,475.4,183,9.34,480600.69,...,9.42,5.51,67102.71,"[9.29, 9.32, 9.34, 9.37, 9.4, 9.42]","[118275.3, 328070.66, 480600.69, 445589.56, 32...","[0.01, 0.03, 0.06, 0.08, 0.11, 0.14, 0.16, 0.1...","[41.34, 41.34, 41.34, 41.3, 41.28, 41.28, 41.3...",['20:2'],[['20:2']],9.32
143,24,20:3,NaN,NaN,NaN,NaN,473.4,183,8.30,690766.69,...,8.40,6.47,115735.96,"[8.24, 8.27, 8.3, 8.32, 8.35, 8.37, 8.4]","[310500.88, 572488.25, 690766.69, 628126.38, 4...","[0.01, 0.03, 0.06, 0.08, 0.11, 0.14, 0.16, 0.1...","[41.22, 41.24, 41.28, 41.34, 41.36, 41.32, 41....",['20:3'],[['20:3']],8.27
149,25,"20:3 (8Z,11Z,14Z)n-6",NaN,NaN,NaN,NaN,405.2,183,8.30,211912.97,...,8.38,6.11,29587.84,"[8.25, 8.28, 8.3, 8.33, 8.36, 8.38]","[54999.18, 145898.62, 211912.97, 199323.78, 14...","[0.01, 0.04, 0.07, 0.09, 0.12, 0.15, 0.17, 0.2...","[41.32, 41.28, 41.32, 41.4, 41.34, 41.3, 41.3,...",['20:3'],[['20:3']],8.27
155,26,"20:3 (8Z,11Z,14Z)n-6,n-9",NaN,NaN,NaN,NaN,365.2,183,8.31,188855.77,...,8.39,6.10,26368.53,"[8.26, 8.28, 8.31, 8.33, 8.36, 8.39]","[61749.06, 143097.17, 188855.77, 165823.98, 11...","[0.02, 0.04, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.38, 41.34, 41.32, 41.32, 42.48, 42.96, 42....",['20:3'],[['20:3']],8.27
166,28,20:4,NaN,NaN,NaN,NaN,471.4,183,7.64,480694.47,...,7.69,6.73,67115.81,"[7.56, 7.59, 7.61, 7.64, 7.67, 7.69]","[72657.73, 282868.03, 474743.5, 480694.47, 339...","[0.01, 0.03, 0.06, 0.08, 0.11, 0.14, 0.16, 0.1...","[41.24, 41.22, 41.28, 41.34, 41.34, 41.32, 41....",['20:4'],[['20:4']],7.61
181,31,"20:5 (5Z,8Z,11Z,14Z,17Z)n-3",NaN,NaN,NaN,NaN,443.3,183,6.70,110158.11,...,6.75,6.11,12304.45,"[6.65, 6.67, 6.7, 6.72, 6.75]","[42310.22, 93655.2, 110158.11, 78164.97, 46428...","[0.01, 0.04, 0.06, 0.09, 0.11, 0.14, 0.17, 0.1...","[41.3, 41.3, 41.32, 41.32, 41.32, 41.28, 41.26...",['20:5'],[['20:5']],6.67
188,35,22:1,NaN,NaN,NaN,NaN,505.4,183,12.57,155917.52,...,12.73,6.43,39185.29,"[12.49, 12.52, 12.54, 12.57, 12.59, 12.62, 12....","[34821.66, 88315.87, 138324.44, 155917.52, 147...","[0.0, 0.03, 0.06, 0.08, 0.11, 0.13, 0.16, 0.19...","[41.2, 41.24, 41.26, 41.22, 41.3, 41.34, 41.34...",['22:1'],[['22:1']],12.54
189,36,22:2,NaN,NaN,NaN,NaN,503.4,183,11.20,164623.83,...,11.34,6.11,32176.37,"[11.15, 11.18, 11.2, 11.23, 11.26, 11.28, 11.3...","[72616.62, 137573.41, 164623.83, 149136.81, 12...","[0.0, 0.03, 0.06, 0.08, 0.11, 0.13, 0.16, 0.19...","[41.26, 41.28, 41.32, 41.32, 41.32, 41.32, 41....",['22:2'],[['22:2']],11.18
194,37,22:6,NaN,NaN,NaN,NaN,495.4,183,7.58,314451.75,...,7.64,6.05,35123.65,"[7.53, 7.56, 7.58, 7.61, 7.64]","[110649.33, 257549.17, 314451.75, 232477.31, 1...","[0.0, 0.03, 0.06, 0.08, 0.11, 0.13, 0.16, 0.19...","[41.18, 41.18, 41.24, 41.28, 41.26, 41.28, 41....",['22:6'],[['22:6']],7.56
204,39,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6",NaN,NaN,NaN,NaN,429.2,183,7.59,92015.65,...,7.64,6.42,12847.46,"[7.51, 7.54, 7.57, 7.59, 7.62, 7.64]","[7189.16, 46100.68, 87015.15, 92015.65, 60886....","[0.01, 0.04, 0.06, 0.09, 0.12, 0.14, 0.17, 0.1...","[41.34, 43.38, 44.32, 43.36, 41.32, 41.26, 41....",['22:6'],[['22:6']],7.56
212,40,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6,n-9",NaN,NaN,NaN,NaN,389.3,183,7.57,160292.03,...,7.65,5.82,22380.39,"[7.52, 7.54, 7.57, 7.6, 7.62, 7.65]","[23035.5, 97191.2, 160292.03, 156165.69, 10207...","[0.02, 0.04, 0.07, 0.09, 0.12, 0.15, 0.17, 0.2...","[41.2, 41.26, 41.32, 41.3, 41.3, 41.3, 41.3, 4...",['22:6'],[['22:6']],7.56
217,41,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6,n-9,n-12",NaN,NaN,NaN,NaN,349.2,183,7.57,216939.06,...,7.65,5.85,30289.59,"[7.52, 7.55, 7.57, 7.6, 7.63, 7.65]","[41436.7, 145455.84, 216939.06, 191392.55, 120...","[0.02, 0.05, 0.07, 0.1, 0.12, 0.15, 0.18, 0.2,...","[41.14, 41.3, 41.34, 41.32, 41.32, 41.34, 41.3...",['22:6'],[['22:6']],7.56
222,42,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6,n-9,n-12,n-15",NaN,NaN,NaN,NaN,309.1,183,7.58,165001.75,...,7.66,5.74,23037.97,"[7.52, 7.55, 7.58, 7.6, 7.63, 7.66]","[36798.7, 115778.87, 165001.75, 140199.56, 856...","[0.02, 0.05, 0.07, 0.1, 0.13, 0.15, 0.18, 0.21...","[41.24, 41.3, 41.36, 41.34, 41.3, 41.24, 47.94...",['22:6'],[['22:6']],7.56

#  TEST EXAMPLE TO PROVE THAT IT MAKES MULTIPLE ROWS OF THE SAME DATA WHEN MTCHING TO OZ OFF

In [104]:
import pandas as pd

# Create sample data for OzON_df
data_on = {
    'FAC': [['18:1', '16:0'], ['20:4'], ['18:0']],
    'Peak_Retention_Time': [5.0, 10.0, 15.0]
}
OzON_df = pd.DataFrame(data_on)

# Create sample data for OzOFF_df
data_off = {
    'FAC': [['16:0'], ['18:1'], ['20:4'], ['20:2']],
    'Peak_Retention_Time': [4.9, 5.1, 10.0, 10.1]
}
OzOFF_df = pd.DataFrame(data_off)

# Function to find matches
def find_matches(OzON_df, OzOFF_df, rt_tolerance=0.5):
    # Prepare the output DataFrame with additional columns for match details
    matched_columns = list(OzON_df.columns) + ['OzOFF_Match', 'OFF_RT']
    df_matched = pd.DataFrame(columns=matched_columns)

    # Iterate through each row in the OzON DataFrame
    for index, ozon_row in OzON_df.iterrows():
        on_fac_list = ozon_row['FAC']
        on_rt = ozon_row['Peak_Retention_Time']

        # Check each row in the OzOFF DataFrame for potential FAC matches
        for _, ozoff_row in OzOFF_df.iterrows():
            off_fac_list = ozoff_row['FAC']
            off_rt = ozoff_row['Peak_Retention_Time']

            # Check for any common FAC entries and within the retention time tolerance
            if any(fac in off_fac_list for fac in on_fac_list) and abs(on_rt - off_rt) <= rt_tolerance:
                # Create a new row for the matched DataFrame including additional match details
                match_data = ozon_row.to_dict()
                match_data['OzOFF_Match'] = off_fac_list
                match_data['OFF_RT'] = off_rt
                df_matched = df_matched.append(match_data, ignore_index=True)

    return df_matched

# Running the function to find matches
df_matched = find_matches(OzON_df, OzOFF_df)
print(df_matched)

            FAC  Peak_Retention_Time OzOFF_Match  OFF_RT
0  [18:1, 16:0]                  5.0      [16:0]     4.9
1  [18:1, 16:0]                  5.0      [18:1]     5.1
2        [20:4]                 10.0      [20:4]    10.0

In [53]:
# Columns to keep from the matched DataFrame
selected_columns = [
    'Lipid_ON', 
    'Biology_ON', 
    'Genotype_ON', 
    'Cage_ON', 
    'Mouse_ON', 
    'Peak_Retention_Time_ON', 
    'Peak_Retention_Time_OFF',
    'Peak_Area_ON',
    'Group_Sample_ON',
    'FAC_ON',
    'FAC_OFF'
]

# Subsetting the DataFrame to only include the desired columns
condensed_df = matched_df[selected_columns]

# Renaming the columns to remove the suffixes for cleaner presentation
condensed_df.columns = [
    'Lipid', 
    'Biology', 
    'Genotype', 
    'Cage', 
    'Mouse', 
    'Peak_Retention_Time_ON', 
    'Peak_Retention_Time_OFF',
    'Peak_Area_ON',
    'Group_Sample_ON',
    'FAC_ON',
    'FAC_OFF'
]
selected_biology = 'dienc'
selected_genotype = '5xFAD'  # Assuming you also have a specific genotype to filter
# Filter DataFrame based on the specified 'Biology' and 'Genotype'
condensed_df = condensed_df[(condensed_df['Biology'] == selected_biology) & (condensed_df['Genotype'] == selected_genotype)]

# Display the condensed DataFrame
# Dropping duplicates from the DataFrame and returning a new DataFrame
condensed_df = condensed_df.drop_duplicates()

# Dropping duplicates inplace (modifying the original DataFrame)
condensed_df.drop_duplicates(inplace=True)
condensed_df.head(50)

Empty DataFrame
Columns: [Lipid, Biology, Genotype, Cage, Mouse, Peak_Retention_Time_ON, Peak_Retention_Time_OFF, Peak_Area_ON, Group_Sample_ON, FAC_ON, FAC_OFF]
Index: []

In [42]:
def contains_comma(fac_list):
    return any(',' in item for item in fac_list)

# Filter DataFrame to exclude rows where 'FAC_OFF' contains any item with a comma
filtered_df = condensed_df[~condensed_df['FAC_OFF'].apply(contains_comma)]

filtered_df

,Lipid,Biology,Genotype,Cage,Mouse,Peak_Retention_Time_ON,Peak_Retention_Time_OFF,Peak_Area_ON,Group_Sample_ON,FAC_ON,FAC_OFF
3692,"10:0 / 18:2 (9Z,12Z)n-6,n-9 / 14:1 (9Z)n-5 / 1...",dienc,5xFAD,FAD231,m2,8.67,8.66,6393.41,2,"['10:0', '18:2', '14:1', '18:3', '16:1', '18:1']",['18:1']
5494,"10:0 / 18:2 (9Z,12Z)n-6,n-9 / 14:1 (9Z)n-5 / 1...",dienc,5xFAD,FAD257,m2,8.65,8.66,5836.64,3,"['10:0', '18:2', '14:1', '18:3', '16:1', '18:1']",['18:1']
17432,13:0,dienc,5xFAD,FAD231,m2,5.50,5.49,6226.35,22,['13:0'],['13:0']
18634,13:0,dienc,5xFAD,FAD257,m2,5.25,5.28,6293.42,23,['13:0'],['13:0']
23896,14:1(9Z),dienc,5xFAD,FAD231,m2,5.41,5.40,2483.85,30,['14:1'],['14:1']
29846,16:0 / 24:1 (15Z)n-9 / 18:1n-3,dienc,5xFAD,FAD231,m2,8.02,7.99,1936082.20,38,"['16:0', '24:1', '18:1']",['16:0']
31198,16:0 / 24:1 (15Z)n-9 / 18:1n-3,dienc,5xFAD,FAD257,m2,8.04,8.02,827704.72,39,"['16:0', '24:1', '18:1']",['16:0']
33968,16:1,dienc,5xFAD,FAD231,m2,7.07,7.06,13527.78,42,['16:1'],['16:1']
34720,16:1,dienc,5xFAD,FAD257,m2,7.06,7.06,14834.47,43,['16:1'],['16:1']
39746,"17:1 / 22:2 (13Z,16Z)n-6",dienc,5xFAD,FAD231,m2,7.96,7.99,1839.33,50,"['17:1', '22:2']",['16:0']
42842,18:0 / 20:1n-3 / 21:1 n-4,dienc,5xFAD,FAD231,m2,8.67,8.66,817.06,54,"['18:0', '20:1', '21:1']",['18:1']
44644,18:0 / 20:1n-3 / 21:1 n-4,dienc,5xFAD,FAD257,m2,8.65,8.66,729.52,55,"['18:0', '20:1', '21:1']",['18:1']
47342,18:1,dienc,5xFAD,FAD231,m2,8.67,8.66,53650.25,58,['18:1'],['18:1']
47794,18:1,dienc,5xFAD,FAD257,m2,8.66,8.66,43680.98,59,['18:1'],['18:1']
78446,d2-16:0,dienc,5xFAD,FAD231,m2,8.00,7.99,63327.61,214,['16:0'],['16:0']
78898,d2-16:0,dienc,5xFAD,FAD257,m2,8.03,8.02,41811.50,215,['16:0'],['16:0']